[[h.30j0zll]]
= INTRODUCCIÓ

[[h.1fob9te]]
== La participació ciutadana en la societat-xarxa

La societat esdevé (en) xarxa. Les tecnologies de la informació i la comunicació (en endavant, TIC) i les pràctiques associades a elles estan canviant irreversiblement el panorama social i polític. Des de l'associació de veïns més petita, passant per  la campanya electoral més intensa, d'una organització de barri o un moviment social, fins a la Unió Europea, les relacions polítiques estan cada vegada més determinades per l’ús de dispositius i tecnologies digitals. El futur de la participació democràtica i l'acció col·lectiva sembla que passarà pel desenvolupament de plataformes digitals i processos híbrids, que renovin les pràctiques tradicionals i les combinin amb les digitals (Fuchs, 2007).

Aquesta transició coincideix amb un declivi del sistema representatiu en les últimes dècades (Norris, 1999; Pharr & Putnam, 2000; Tormey, 2015), que ha contribuït al qüestionament de la legitimitat i el sentit de la democràcia mateixa, reduïda i identificada sovint amb aquest sistema (Crouch, 2004; Keane, 2009; Streeck, 2016). Diferents autors han utilitzat el terme "postrepresentació" per referir-se al buidatge de poder i sentit de les institucions representatives que van de la globalització a la desafecció i el desempoderament de la ciutadania (Brito Vieira and Runciman, 2008; Keane, 2009; Rosanvallon , 2011; Tormey, 2015). Els diferents intents de potenciar la participació han resultat insuficients per revertir aquestes tendències (Keane, 2011; Tormey, 2015).

A aquesta crisi política de llarg recorregut cal sumar la crisi financera i econòmica de 2008, la gestació no pot separar-se d'aquesta crisi prèvia. No obstant això, enfront de la crisi, milions de persones es van mobilitzar amb la intenció, no només de demanar, sinó també d'experimentar i construir una democràcia real. L'esdeveniment clau, en aquest sentit, va ser el moviment-xarxa 15M. En un context d’hipermediació tecnològica, les tecnologies de la informació i la comunicació, que van servir durant els 80 i 90 per accelerar els fluxos financers i la globalització (Castells, 1996) es van convertir en espais i dispositius crucials en la re-apropiació multitudinària de la política, així com d'experimentació democràtica (Martinet Ros et al., 2015).

Després de quatre anys amb nombrosos èxits i fracassos, al maig de 2015, noves iniciatives polítiques ciutadanes van aconseguir prendre el poder en algunes de les principals ciutats del país, incloent-hi Barcelona. En això, seguien l'onada del que ha passat en països com Islàndia, on la crisi econòmica va donar pas a un període re-apropiació ciutadana de les institucions i de fèrtil innovació democràtica, recolzada en l'ús intensiu i creatiu de les TIC.

Des del 15M, la majoria dels experiments que apunten noves formes de democràcia participativa i deliberativa (Barber, 1984; Habermas, 1994, 1996; Della Porta 2013) han estat intervinguts tecnològicament. Tal com mostra el cas d'Islàndia (però també d'altres, com Finlàndia), els processos democratitzadors de mobilització i empoderament ciutadans requereixen una articulació tecnopolítica (Rodotà 1997; Martinet Ros et al., 2015) per assolir la seva màxima riquesa i capacitat. La tecnopolítica és el resultat de l'esdevenir polític de les tecnologies i el re-assemblatge tecnològic de la política, de la coevolució i coproducció de polítiques i tecnologies. En les formes de participació i deliberació tecnopolítica les pràctiques, els espais i els processos digitals i presencials es connecten i retroalimenten, adquirint una dimensió multicapa. Aquests dispositius participatius estan orientats a incrementar el nombre, varietat i paritat entre els actors que "prenen part" en el govern comú de la ciutat, ampliant i enriquint els àmbits, formes i períodes en què això té lloc, i contribuint a potenciar una intel·ligència col·lectiva (Levy, 1997) capaç de fer front a la complexitat urbana contemporània. La tecnopolítica ha d'afrontar els nombrosos límits de la que s'ha anomenat "democràcia digital" (Hindman, 2008), començant per alliberar-se de les narratives i pràctiques tecnocèntriques i tecnoptimistes al voltant de la participació intervinguda digitalment.

La construcció de nous processos de participació es dóna en un context ple d'oportunitats i riscos. L’elaboració del programa de govern el 2015 i el Programa de Actuación Municipal (PAM) 2016-2019 per a la ciutat de Barcelona, atorga un lloc central a la participació i, en concret, a la innovació i al desenvolupament de nous models de participació democràtica. El PAM, ​​desenvolupat participativament per milers de persones, dona resposta a  una clara demanda social que exigeix ​​redissenyar profundament el sistema democràtic i els mecanismes de participació. Això, però, té lloc en un context definit per: a) grans sectors poblacionals exclosos política, econòmica i socialment; b) una creixent dificultat d'accés a la participació derivada de la situació de crisi econòmica; c) una crisi de la legitimitat i d'operativitat del sistema democràtic representatiu i de l'administració pública; d) una enorme dependència tecnològica d'infraestructures i serveis corporatius privats; e) un context legal i polític advers a la democràcia directa, l'autonomia social i la sobirania territorial; f) un desavantatge institucional abismal en la comprensió de la complexitat social a través de tècniques d'anàlisi de dades i de models de comportament social que posseeixen les grans corporacions tecnològiques i de serveis articulats digitalment.

[[h.3znysh7]]
== Control de les dades i infraestructures digitals per a la democràcia

En el context de les noves configuracions del capitalisme informacional (Castells, 1996), l'anomenat "capitalisme de dades" (Lohr, 2015; Morozov, 2015) o "de la vigilància" (Zuboff, 2015), les noves infraestructures digitals de la democràcia corren el risc de contribuir a dinàmiques contràries a principis com la privacitat o la sobirania tecnològica. Les plataformes privatives, tancades, gens transparents i orientades a l'explotació de l'activitat social per al benefici corporatiu, operen com a espais no-democràtics que cada vegada ocupen més àrees de la vida social. Aquest model resulta particularment perillós quan del què parlem és, precisament, de les noves infraestructures i de processos de la democràcia.

Davant del model privatiu i corporatiu d'infraestructures, el model públic-comú, que creiem ha d'inspirar el desenvolupament de decidim.barcelona, ​​s'orienta al desenvolupament de plataformes en què el disseny, la propietat i la gestió són lliures, oberts i participatius, compartits entre treballadors/es públiques i ciutadania (organitzada i no organitzada). Sota aquest model, no només el codi de la plataforma, sinó també les dades que es generen en ella, són manejats i apropiats seguint lògiques de gestió pública i comuna. L'obertura a la participació de totes i de qualsevol, marca definitòria del comú com a principi polític (per contraposició a l'esfera del què és privat i fins i tot el públic-estatal --- Laval & Dardot, 2015), sembla una condició bàsica perquè les infraestructures de participació puguin ser-ho de manera plena. La participació ha de ser, en aquest sentit, recursiva: ha d'ajudar a definir i establir les condicions infraestructurals de la seva pròpia existència, i ha d’afectar el disseny, el desenvolupament i la gestió de les plataformes digitals de participació, així com dels processos i resultats (p.ex .: dades) que es generen en elles.

En mans de grans corporacions de serveis digitals, l'organització algorísmica de la vida social i, en en el cas que ens ocupa, de la participació política, suposa un risc democràtic i de sobirania tecnològica que només un esforç públic-comú en infraestructures digitals pot revertir. Només plataformes basades en programari lliure, obertes, transparents, segures i de gestió público-comuna ofereixen garanties a l'hora de construir democràcies de major qualitat. La democràcia del futur s’ha de construïr, per tant, sobre infraestructures democràtiques.
