[[h.30j0zll]]
= INTRODUCCIÓN

[[h.1fob9te]]
== La participación ciudadana en la sociedad red

La sociedad se convierte en red. Las tecnologías de la información y de la comunicación (en adelante, TIC) y las prácticas asociadas a ellas están cambiando irreversiblemente el panorama social y político. Desde la asociación de vecinos más pequeña, pasando por la campaña electoral más intensa, de una organización de barrio o un movimiento social, hasta la Unión Europea, las relaciones políticas están cada vez más determinadas por el uso de dispositivos y tecnologías digitales. Así, el futuro de la participación democrática y la acción colectiva dependerá del desarrollo de plataformas digitales y procesos híbridos que renueven las prácticas tradicionales y las combine con las digitales.

Esta transición coincide con un declive del sistema representativo en las últimas décadas (Norris, 1999; Pharr y Putnam, 2000; Tormey, 2015), que ha contribuido al cuestionamiento de la legitimidad y el sentido de la propia democracia, reducida e identificada frecuentemente con este sistema (Crouch, 2004; Keane, 2009; Streeck, 2016). Diversos autores han utilizado el término posrepresentación para referirse al vaciado de poder y sentido de las instituciones representativas que van de la globalización a la desafección y el desempoderamiento de la ciudadanía (Brito Vieira y Runciman, 2008; Keane, 2009; Rosanvallon, 2011; Tormey, 2015). Los diferentes intentos de potenciar la participación han resultado insuficientes para revertir estas tendencias (Keane, 2011; Tormey, 2015).

A esta crisis política de largo recorrido hay que sumar la crisis financiera y económica del 2008; su gestación no puede separarse de esta crisis previa. No obstante, frente a la crisis, millones de personas se movilizaron con la intención no sólo de exigir, sino también de experimentar y construir una democracia real. El acontecimiento clave, en este sentido, fue el movimiento red 15M. En un contexto de hipermediación tecnológica, las TIC, que durante los años ochenta y noventa sirvieron para acelerar los flujos financieros y la globalización (Castells, 1996), se convirtieron en espacios y dispositivos cruciales en la reapropiación multitudinaria de la política, así como de experimentación democrática (Martinet Ros et al., 2015).

Tras cuatro años de numerosos éxitos y fracasos, en mayo del 2015, nuevas iniciativas políticas ciudadanas consiguieron tomar el poder en algunas de las principales ciudades del país, incluyendo Barcelona. Así, seguían la oleada de lo ocurrido en países como Islandia, donde la crisis económica dio paso a un periodo de reapropiación ciudadana de las instituciones y de fértil innovación democrática, reforzada en el uso intensivo y creativo de las TIC.

Desde el 15M, la mayoría de los experimentos que apuntan a nuevas formas de democracia participativa y deliberativa (Barber, 1984; Habermas, 1994, 1996; Della Porta, 2013) han sido intervenidos tecnológicamente. Tal como muestra el caso de Islandia (pero también otros, como el de Finlandia), los procesos democratizadores de movilización y empoderamiento ciudadanos requieren una articulación tecnopolítica (Rodotà, 1997; Martinet Ros et al., 2015) para alcanzar su máxima riqueza y capacidad. La tecnopolítica es el resultado del devenir político de las tecnologías y el reensamblaje tecnológico de la política, de la coevolución y la coproducción de políticas y tecnologías. En las formas de participación y deliberación tecnopolítica, las prácticas, los espacios y los procesos digitales y presenciales se conectan y retroalimentan, adquiriendo una dimensión multicapa. Estos dispositivos participativos están orientados a incrementar el número, la variedad y la paridad entre los actores que “toman parte” en el gobierno común de la ciudad, ampliando y enriqueciendo los ámbitos, las formas y los periodos en que eso tiene lugar, y contribuyendo a potenciar una inteligencia colectiva (Levy, 1997) capaz de hacer frente a la complejidad urbana contemporánea. La tecnopolítica tiene que afrontar los numerosos límites de la que se ha denominado democracia digital (Hindman, 2008), empezando por liberarse de las narrativas y prácticas tecnocéntricas y tecnooptimistas en torno a la participación intervenida digitalmente.

La construcción de nuevos procesos de participación se da en un contexto repleto de oportunidades y riesgos. La elaboración del programa de gobierno en el 2015 y el Programa de actuación municipal (PAM) 2016-2019 para la ciudad de Barcelona, otorga un lugar central a la participación y, en concreto, a la innovación y al desarrollo de nuevos modelos de participación democrática. El PAM, ​​desarrollado con la participación de miles de personas, da respuesta a una clara demanda social que exige ​​rediseñar profundamente el sistema democrático y los mecanismos de participación. Esto, sin embargo, tiene lugar en un contexto definido por a) grandes sectores poblacionales excluidos política, económica y socialmente; b) una creciente dificultad de acceso a la participación derivada de la situación de crisis económica; c) una crisis de la legitimidad y de operatividad del sistema democrático representativo y de la Administración pública; d) una enorme dependencia tecnológica de infraestructuras y servicios corporativos privados; e) un contexto legal y político adverso a la democracia directa, la autonomía social y la soberanía territorial; y f) una desventaja institucional abismal en la comprensión de la complejidad social a través de técnicas de análisis de datos y de modelos de comportamiento social que poseen las grandes corporaciones tecnológicas y de servicios articulados digitalmente.

[[h.hfcddqdihctf]]
[[h.3znysh7]]
== Control de los datos y las infraestructuras digitales para la democracia

En el contexto de las nuevas configuraciones del capitalismo informacional (Castells, 1996), el denominado capitalismo de datos (Lohr, 2015; Morozov, 2015) o capitalismo de la vigilancia (Zuboff, 2015), las nuevas infraestructuras digitales de la democracia corren el riesgo de contribuir a dinámicas contrarias a principios como la privacidad o la soberanía tecnológica. Las plataformas privativas, cerradas, nada transparentes y orientadas a la explotación de la actividad social para la ganancia corporativa, operan como espacios no democráticos que cada vez ocupan más áreas de la vida social. Este modelo resulta particularmente peligroso cuando de lo que hablamos es, precisamente, de las nuevas infraestructuras y de procesos de la democracia.

Ante el modelo privativo y corporativo de infraestructuras, el modelo público-común, que creemos debe inspirar el desarrollo de decidim.barcelona, ​​se orienta hacia el desarrollo de plataformas en las que el diseño, la propiedad y la gestión son libres, abiertos y participativos, compartidos entre trabajadores y trabajadoras públicos y la ciudadanía (organizada y no organizada). Bajo este modelo, no solo el código de la plataforma, sino también los datos que se generan en ella, se manejan y se apropian siguiendo lógicas de gestión pública y común. La apertura a la participación de todas y de cualquiera, marca definitoria del común como principio político —por contraposición a la esfera de lo que es privado e incluso de lo público-estatal (Laval y Dardot, 2015)—, parece una condición básica para que las infraestructuras de participación puedan serlo de manera plena. La participación debe ser, en este sentido, recursiva: debe ayudar a definir y establecer las condiciones de infraestructura de su propia existencia, y debe incidir en el diseño, el desarrollo y la gestión de las plataformas digitales de participación, así como en los de los procesos y resultados (por ejemplo, datos) que se generan en ellas.

En manos de grandes corporaciones de servicios digitales, la organización algorítmica de la vida social y, en el caso que nos ocupa, de la participación política, supone un riesgo democrático y de soberanía tecnológica que solo un esfuerzo público-común en infraestructuras digitales puede revertir. Solo plataformas basadas en software libre, abiertas, transparentes, seguras y de gestión público-común ofrecen garantías a la hora de satisfacer esta demanda y construir democracias de mayor calidad. La democracia del futuro debe construirse, por tanto, sobre infraestructuras democráticas.
